# main_second.yml 파일의 내용입니다.

name: 두 번째 이미지 수정 (일회성)

on:
  # 이 워크플로우는 수동 실행만 가능하도록 설정합니다.
  workflow_dispatch:

jobs:
  run-second-script:
    runs-on: self-hosted # 사장님의 PC 러너에서 실행

    steps:
      # 1. 저장소 코드를 PC 러너로 내려받습니다.
      - name: 저장소 코드 체크아웃
        uses: actions/checkout@v3

      # 2. 파이썬 환경을 설정합니다.
      - name: 파이썬 환경 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 필요한 라이브러리들을 설치합니다.
      - name: 필요한 라이브러리 설치
        run: pip install requests beautifulsoup4 lxml

      # 4. main_second.py 스크립트를 실행합니다.
      - name: 두 번째 이미지 수정 스크립트 실행
        env:
          COUPANG_ACCESS_KEY: ${{ secrets.COUPANG_ACCESS_KEY }}
          COUPANG_SECRET_KEY: ${{ secrets.COUPANG_SECRET_KEY }}
          PYTHONIOENCODING: utf-8
        run: python main_second.py